### ISSUE TITLE
Use https or http

### ISSUE THREAD

**Issue by manuel-rubio** [joshuafleck/ex_ngrok#15]
Is it possible to use https in addition to http to retrieve the URL?

**Comment by joshuafleck** [comment]
Hi @manuel-rubio! Apologies for the delayed reply, I only just saw this. Let me have a look this weekend and get back to you.

**Comment by joshuafleck** [comment]
Hi @manuel-rubio - please see: https://github.com/joshuafleck/ex_ngrok/pull/17

By allowing you to specify `https` as the protocol, does this solve your problem?

**Comment by manuel-rubio** [comment]
yes, thanks @joshuafleck
